"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"/api";
const stages=["normalize","ledger_index","match","exception_reasoning","posting"];
const label={normalize:"Normalize payments",ledger_index:"Index open AR",match:"Verify candidates",exception_reasoning:"Reason exceptions",posting:"Create postings"};
const stageDetail={normalize:"Deterministic + GPT-5.6",ledger_index:"Deterministic code",match:"Deterministic code",exception_reasoning:"GPT-5.6 + safety policy",posting:"Deterministic code"};
const money=(n,c="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency:c}).format(Number(n));
const displayDate=value=>value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)):"—";
function dateEvidence(payment,statementDate){
 if(!payment||payment.payment_type!=="CHECK"||!payment.date||!statementDate)return null;
 if(payment.date>statementDate)return {type:"Post-dated check",detail:`Check date ${displayDate(payment.date)} is after statement date ${displayDate(statementDate)}. Posting is blocked until the check date.`};
 const age=Math.round((Date.parse(`${statementDate}T00:00:00Z`)-Date.parse(`${payment.date}T00:00:00Z`))/86400000);
 if(age>180)return {type:"Stale check",detail:`Check date ${displayDate(payment.date)} is ${age} days before statement date ${displayDate(statementDate)}; the policy limit is 180 days.`};
 return null;
}
export default function Home(){
 const [data,setData]=useState(null),[samples,setSamples]=useState([]),[sample,setSample]=useState("04"),[done,setDone]=useState([]),[out,setOut]=useState([]),[run,setRun]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("sample");if(requested)setSample(requested)},[]);
 useEffect(()=>{fetch(`${API}/samples`).then(x=>x.ok?x.json():Promise.reject(new Error("Unable to load samples"))).then(x=>setSamples(x.samples||[])).catch(()=>setSamples([]))},[]);
 useEffect(()=>{let cancelled=false;setData(null);setDone([]);setOut([]);setRun("");fetch(`${API}/demo-data?sample=${sample}`).then(x=>x.ok?x.json():Promise.reject(new Error("Unable to load sample"))).then(x=>{if(!cancelled)setData(x)}).catch(()=>{if(!cancelled)setData(null)});return()=>{cancelled=true}},[sample]);
 function chooseSample(event){const next=event.target.value;const url=new URL(window.location.href);url.searchParams.set("sample",next);window.history.replaceState({},"",url);setSample(next)}
 async function reconcile(){if(!data)return;setBusy(true);setDone([]);setOut([]);
  const r=await fetch(`${API}/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bank_data:data.bank_statement,ar_data:data.open_ar})});
  const reader=r.body.getReader();let buf="";while(true){const {value,done:closed}=await reader.read();if(closed)break;buf+=new TextDecoder().decode(value);const parts=buf.split("\n\n");buf=parts.pop();for(const p of parts){if(!p.startsWith("data: ")||p==="data: [DONE]")continue;const e=JSON.parse(p.slice(6));setRun(e.run_id||run);if(e.event==="stage")setDone(v=>v.includes(e.stage)?v:[...v,e.stage]);if(e.event==="stage"&&e.output)setOut(v=>[...v,e.output]);}}setBusy(false)}
 const payments=data?.bank_statement?.transactions||[];
 const ledger=data?.open_ar||{};
 const invoices=ledger.invoices||[];
 const aliasesByCustomer=(ledger.payer_alias_registry||[]).reduce((all,alias)=>{(all[alias.canonical_customer_id]||=[]).push(alias);return all;},{});
 const parentsByChild=(ledger.parent_child_hierarchy||[]).reduce((all,parent)=>{parent.children.forEach(child=>{(all[child]||=[]).push(parent.parent_name)});return all;},{});
 const nettingCustomers=new Set((ledger.intercompany_netting||[]).filter(item=>item.net_agreement_active).map(item=>item.customer_id));
 const paymentsById=new Map(payments.map(payment=>[payment.txn_id,payment]));
 return <main>
  <header className="hero">
   <div><div className="hero-tags"><p className="eyebrow">OpenAI · GPT-5.6</p><span className="build-badge">Built for OpenAI Build Week — Codex + GPT-5.6</span></div><h1>Ledger<br/>Sense</h1><p className="subtitle">Verified matching, with human-safe exception routing.</p></div>
   <div className="hero-actions"><label className="sample-picker"><span>Demo dataset</span><select value={sample} onChange={chooseSample} disabled={busy||!samples.length} aria-label="Choose a demo dataset">{samples.map(item=><option key={item.sample_id} value={item.sample_id}>{item.sample_id} — {item.label}</option>)}</select></label><button disabled={busy||!data} onClick={reconcile}><i>{busy?"◌":"↗"}</i>{busy?"Running pipeline…":"Run synthetic demo"}</button></div>
  </header>
  <section className="pipeline" aria-label="Reconciliation pipeline">{stages.map((s,i)=><div className={`stage ${done.includes(s)?"on":""}`} key={s}><b>{done.includes(s)?"✓":String(i+1).padStart(2,"0")}</b><div><strong>{label[s]}</strong><small>{stageDetail[s]}</small></div></div>)}</section>
  <section className="comparison-head"><div><p className="section-kicker">Reconciliation workspace</p><h2>Payments, resolved.</h2></div><p>{busy?"Streaming agent decisions in real time.":"Run the sample pipeline to see each verified decision."}</p></section>
  <section className="source-panels">
   <article className="panel before"><div className="panel-head"><div><p className="panel-label">Input</p><h3>Bank payments</h3></div><em>{payments.length} transactions</em></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Date</th><th>Payer</th><th>Remittance</th><th className="amount">Amount</th></tr></thead><tbody>{payments.map(p=><tr key={p.txn_id}><td className="mono">{p.txn_id}</td><td className="date-cell">{displayDate(p.date)}</td><td className="payer">{p.payer_raw}</td><td className="muted">{p.remittance_text||"—"}</td><td className="amount">{money(p.amount,p.currency)}</td></tr>)}</tbody></table></div></article>
   <article className="panel ledger"><div className="panel-head"><div><p className="panel-label">Internal ledger</p><h3>Open AR</h3></div><em>{invoices.length} invoices</em></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Customer / aliases</th><th>Due date</th><th className="amount">Open amount</th><th>Flags</th></tr></thead><tbody>{invoices.map(invoice=>{const aliases=aliasesByCustomer[invoice.customer_id]||[];const flags=[invoice.status!=="OPEN"&&invoice.status.replaceAll("_"," "),invoice.dispute_reason&&"dispute",aliases.some(alias=>alias.match_type.includes("FACTOR"))&&"factoring",parentsByChild[invoice.customer_id]?.length&&"parent payer",nettingCustomers.has(invoice.customer_id)&&"intercompany"].filter(Boolean);return <tr key={invoice.invoice_id}><td className="mono">{invoice.invoice_id}</td><td><span className="customer">{invoice.customer_name}</span>{aliases.length>0&&<span className="aliases">{aliases.map(alias=>`${alias.payer_alias} · ${alias.match_type.replaceAll("_"," ")}`).join("; ")}</span>}</td><td className="date-cell">{displayDate(invoice.due_date)}</td><td className="amount">{money(invoice.open_amount,invoice.currency)}</td><td><span className="flag-list">{flags.length?flags.map(flag=><mark className={`flag ${flag.replaceAll(" ","_")}`} key={flag}>{flag}</mark>):<span className="muted">—</span>}</span></td></tr>})}</tbody></table></div></article>
  </section>
  <section className="policy-panel panel" aria-label="Deterministic policy rules"><div className="panel-head"><div><p className="panel-label">Safety policy</p><h3>Policy rules applied before posting</h3></div><em>Deterministic hard gates</em></div><div className="policy-grid"><div><strong>Post-dated checks</strong><span>Hold when the check date is after the statement date.</span></div><div><strong>Stale checks</strong><span>Route to review when a check is more than 180 days old.</span></div><div><strong>Compliance &amp; disputes</strong><span>Compliance/legal holds and disputed invoices cannot be auto-posted.</span></div><div><strong>Auto-post threshold</strong><span>Requires a code-verified allocation with at least 0.95 confidence.</span></div></div></section>
  <section className="results-section">
   <article className="panel after"><div className="panel-head"><div><p className="panel-label">Verified output</p><h3>Posting instructions</h3></div><em>{out.length} decisions</em></div>{out.length?<div className="result-list">{out.map(p=>{const evidence=dateEvidence(paymentsById.get(p.transaction_id),data?.bank_statement?.statement_date);return <div className="result" key={p.transaction_id}><div className="result-top"><span className="mono">{p.transaction_id}</span><mark className={p.route}>{p.route.replaceAll("_"," ")}</mark></div><div className="decision"><div><p className="decision-label">Matched invoices</p><strong>{p.invoice_ids.join(", ")||"No verified invoice"}</strong></div><div className="confidence"><span>{Math.round(p.confidence*100)}%</span><small>routing confidence</small></div></div><div className="rationale"><span className="spark">✦</span><div><p>{p.reason}</p>{evidence&&<div className="date-evidence"><strong>{evidence.type}</strong><span>{evidence.detail}</span></div>}{p.entity_resolution&&<div className={`entity-meta ${p.entity_resolution.resolved_entity?"resolved":"unresolved"}`}><strong>{p.entity_resolution.resolved_entity||"Entity unresolved"}</strong><span>{Math.round((p.entity_resolution.confidence||0)*100)}% entity confidence</span></div>}{p.entity_resolution?.rationale&&<small>Entity resolution: {p.entity_resolution.rationale}</small>}</div></div></div>})}</div>:<div className="empty"><span>✦</span><strong>Your verified decisions will appear here.</strong><p>Each result includes an AI rationale, confidence score, and deterministic invoice match.</p></div>}</article>
  </section>
  <footer><span>All amounts are verified in code with Decimal.</span><span>GPT-5.6 never creates allocations.</span>{run&&<span>Audit run <code>{run}</code></span>}</footer>
 </main>
}
